const BAD_REQUEST_STATUS = 400;
const UNAUTHORIZED_STATUS = 401;
const FORBIDDEN_STATUS = 403;
const NOT_FOUND_STATUS = 404;
const CONFLIICT_STATUS = 409;
const INTERNAL_SERVER_ERROR_STATUS = 500;

module.exports = {
  BAD_REQUEST_STATUS,
  UNAUTHORIZED_STATUS,
  FORBIDDEN_STATUS,
  NOT_FOUND_STATUS,
  CONFLIICT_STATUS,
  INTERNAL_SERVER_ERROR_STATUS,
};
